### ISSUE TITLE
Upgrade to PHP 8.3

### ISSUE THREAD

**Issue by spaze** [spaze/michalspacek.cz#159]
Followup to #53 (Upgrade to PHP 8.2)

- [x] #161
- [x] #163
- [x] oerdnj/deb.sury.org#2034
- [x] #251 ⬆️ even though the issue is not closed yet
- [x] nette/command-line#1
- [x] efabrica-team/phpstan-latte#451
- [x] #252
